@api = http://localhost:3000/api/traslados


GET {{api}}
###Mostrar todos los traslados Activos

GET {{api}}/2
###Mostrar traslado por folio

GET  {{api}}/count
###Contat todos los traslados activos

POST {{api}}
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjA0LCJpYXQiOjE2Mjg4ODM0NjYsImV4cCI6MTYyODk2OTg2Nn0.koSPUx8qUVEMxkfmk00i8O6g1rZLpPtpl1reiDjF04Q
Content-Type: application/json; charset=utf-8

{
    "adquiriente" : "Hatake Kakashi",
    "enajenante" : "Hinata Hyūga",
    "num_escr" : "84471",
    "f_escr" : "2021-08-12",
    "area" : "82"
}
###Insertar un traslado

DELETE  {{api}}/2
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjA0LCJpYXQiOjE2Mjg4ODM0NjYsImV4cCI6MTYyODk2OTg2Nn0.koSPUx8qUVEMxkfmk00i8O6g1rZLpPtpl1reiDjF04Q
###Borrar uns traslado cambiando su clave

PUT {{api}}/2
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjA0LCJpYXQiOjE2Mjg4ODM0NjYsImV4cCI6MTYyODk2OTg2Nn0.koSPUx8qUVEMxkfmk00i8O6g1rZLpPtpl1reiDjF04Q
Content-Type: application/json; charset=utf-8

{
  "adquiriente" : "Yahami Light",
  "enajenante" : "Stark Tony",
  "num_escr" : "851209",
  "f_act" : "2021-08-10"
}